### PR TITLE
[TS compile] Fix torch_mlir.compile

### PR DESCRIPTION
**Pull request by Devjiu**
This commit allows to use `torch_mlir.compile` that uses TorcScript under the hood.

e.g. to verify:
```sh
python -m e2e_testing.main -c "linalg" -f "MLP_basic" -v -s
```

Also makes float comparison a litlle less strict.

### CODE REVIEW

**Comment by Devjiu** [comment]
Test results will be here: https://github.com/intel-ai/graph-compiler-playground/actions/runs/7747509558

**Review by ienkovich — APPROVED** [review]
Changes in mlp.py seem unrelated. Otherwise looks good!

**Comment by Devjiu** [comment]
> Changes in mlp.py seem unrelated. Otherwise looks good!

yes, can do in separate pr, it's micro-refactor

**Comment by Devjiu** [comment]
> > Changes in mlp.py seem unrelated. Otherwise looks good!
> 
> yes, can do in separate pr, it's micro-refactor

updated, mlp refactor removed

**Pull request merged**
